[env:ttgo_tcamera_plus]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = default.csv
board_build.filesystem = littlefs
build_flags = \
    -DCORE_DEBUG_LEVEL=4 \
    -DBOARD_HAS_PSRAM \
    -mfix-esp32-psram-cache-issue \
    -DUSER_SETUP_LOADED=1 \
    -DST7789_DRIVER \
    -DTFT_WIDTH=240 \
    -DTFT_HEIGHT=240 \
    -DTFT_MOSI=19 \
    -DTFT_SCLK=21 \
    -DTFT_CS=12 \
    -DTFT_DC=15 \
    -DTFT_RST=-1 \
    -DTFT_BL=2 \
    -DTOUCH_CS=-1 \
    -DSPI_FREQUENCY=40000000 \
    -DTFT_BACKLIGHT_ON=1
lib_deps = \
    bblanchon/ArduinoJson @ ^6.21.3 ; # JSON config handling
    bodmer/TFT_eSPI @ ^2.5.43 ; # ST7789 TFT driver using build_flags configuration
    arduino-libraries/SD @ ^1.2.4 ; # SPI SD card support
